# Generated by Django 5.2.3 on 2025-08-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookingAPI', '0001_initial'),
        ('ownerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerAPI.ground'),
        ),
    ]
