# Generated by Django 5.2.3 on 2025-07-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
