# Generated by Django 5.2.5 on 2025-11-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='refund_amount',
        ),
    ]
