# Generated by Django 5.2.3 on 2025-08-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0002_remove_booking_end_time_remove_booking_start_time_and_more'),
        ('ownerAPI', '0004_remove_ownerprofile_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ownerAPI.ground'),
        ),
    ]
