# Generated by Django 5.2.3 on 2025-08-05 15:51

import datetime
import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ground Name')),
                ('ground_type', models.CharField(choices=[('5A', '5-a-side'), ('7A', '7-a-side'), ('MAT', 'Mat Futsal'), ('TURF', 'Turf'), ('WOOD', 'Wooden Floor')], max_length=10, verbose_name='Ground Type')),
                ('opening_time', models.TimeField(default=datetime.time(5, 0), verbose_name='Opening Time')),
                ('closing_time', models.TimeField(default=datetime.time(22, 0), verbose_name='Closing Time')),
                ('price', models.IntegerField(default=0, verbose_name='Base Price')),
                ('use_dynamic_pricing', models.BooleanField(default=False, verbose_name='Use Dynamic Pricing')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futsal_name', models.CharField(max_length=255, verbose_name='Futsal Name')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='Location Coordinates')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='GroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ground_images/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_images', to='ownerAPI.ground')),
            ],
        ),
        migrations.CreateModel(
            name='GroundPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('price_per_hour', models.PositiveIntegerField(verbose_name='Price per Hour')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='ownerAPI.ground')),
            ],
            options={
                'verbose_name': 'Ground Pricing',
                'verbose_name_plural': 'Ground Pricing Rules',
                'ordering': ['ground', 'day_of_week', 'start_time'],
            },
        ),
    ]
