# Generated by Django 5.2.3 on 2025-08-05 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ownerAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ground',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grounds', to='ownerAPI.ownerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='groundpricing',
            unique_together={('ground', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
