# Generated by Django 5.2.5 on 2025-09-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAPI', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroundPricing',
        ),
    ]
