# Generated by Django 5.2.3 on 2025-07-31 05:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerAPI', '0003_alter_ownerprofile_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='ground_type',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='opening_time',
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_type', models.CharField(choices=[('5A', '5-a-side'), ('7A', '7-a-side'), ('MAT', 'Mat Futsal'), ('TURF', 'Turf'), ('WOOD', 'Wooden Floor')], max_length=10)),
                ('opening_time', models.TimeField(default=datetime.time(5, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('price', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grounds', to='ownerAPI.ownerprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='groundimage',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_images', to='ownerAPI.ground'),
        ),
    ]
