# Generated by Django 5.2.4 on 2025-07-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/pfp.png', null=True, upload_to='profile_pics/'),
        ),
    ]
