# Generated by Django 5.2.5 on 2025-08-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
